---
detectors:
  BooleanParameter:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  UncommunicativeVariableName:
    accept:
      - e
  FeatureEnvy:
    exclude:
      - 'Nanites::Commands::Compound#execute'
      - 'Nanites::Commands::Compound#run'
      - 'Nanites::Compounds::FirstSomeCompound#execute!'

directories:
  "lib/nanites/compounds":
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - spec