---
detectors:
  UtilityFunction:
    public_methods_only: true
  UncommunicativeVariableName:
    accept:
      - e
  FeatureEnvy:
    exclude:
      - 'Nanites::Actions::Compound#execute'

exclude_paths:
  - spec